# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e523809d20926bfeee38fcd5f58b48fe1ed2086d32e246dea9a24dcb4ecd4da02d24daa7b6923612954c2c711de3d43ecea25923da228314e6eaf79b4dc44c6e

test:
  secret_key_base: 02f49e99ffadcde4c2e227fd5e5ba0522fde56ddfd4875612808f44a72248c12acba98f93e1dbda628c8a62b710051c44012c33ff1e20fe47bac023d44a84346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
